# See: https://taskfile.dev/api/

version: "3"

tasks:
  migrate:
    aliases:
      - m
    desc: "Run mifrations"
    cmds:
      - go run ./cmd/migrator --storage-path=./storage/sso.db --migrations-path=./migrations
  run:
    desc: "Run sso app"
    cmds:
      - go run cmd/sso/main.go --config=./config/local.yaml
  migrate_test:
    aliases:
        - mtest
    desc: "Run sso app"
    cmds:
      - go run ./cmd/migrator/main.go --storage-path=./storage/sso.db --migrations-path=./tests/migrations --migrations-table=migrations_test