# See: https://taskfile.dev/api/

version: "3"

tasks:
  migrate:
    aliases:
      - mgr
    desc: "Generate code from proto files"
    cmds:
      - go run ./cmd/migrator --storage-path=./storage/sso.db --migrations-path=./migrations